### ISSUE TITLE
Merge efforts ?

### ISSUE THREAD

**Issue by hugolpz** [rkosov/Lingua-Libre-User-Audio-Downloader#1]
Hello Rkosov, 

You may want to check up https://github.com/sulochanaviji/Wiki-bulk-downloader . @Sulochanaviji started to code this python/Django project few days ago, for the 2022 hackathon. Depending of your needs and time resources, it could be good for you to join that more advanced project. Given you yourself just coded the Python [Lingua-Libre-User-Audio-Downloader script](https://github.com/rkosov/Lingua-Libre-User-Audio-Downloader), you therefore have a most relevant expertise to provide feedbacks and team up with Sulochanaviji.

**Comment by rkosov** [comment]
@hugolpz That's a great project. Thank you for letting me know. I've thought about it carefully and I believe that the two projects have different objectives. This projects seeks to be an extremely lightweight program to download the user pronunciations by querying the Lingua Libre database and then finding the download links on Common by doing some regular expression searches. The Wiki Bulk Downloader queries the Common database (which requires a login) and generally operates on a specific category. While it can be used to download a user's pronunciations, this will only really work if their pronunciations are in a specific category and less than 500 (the program limits the files to this number). I think that it's a great program, but I want to create a way for a user to quickly obtain all their pronunciations. In this way, they can truly own their own contributions and reuse them as they see fit allowing Lingua Libre to become a hub for recording and preserving pronunciations without taking away control from speakers.
